# FROM nginx:alpine

# COPY /build ./var/www/build

# ADD nginx.conf /etc/nginx/conf.d/default.conf

# CMD [ "nginx", "-g", "daemon off;"]

# Step 1: Use the official Node.js image from Docker Hub
FROM node:20.6.0

# Step 2: Set the working directory inside the container
WORKDIR /Frontend-TT

# Step 3: Copy package.json and package-lock.json first to take advantage of caching
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy the rest of the application code
COPY . .

# Step 6: Build the React app
RUN npm run build

# Step 7: Expose the port the app will run on (optional if needed)
EXPOSE 3000

# Step 8: Start the app (optional depending on your setup)
CMD ["npm", "start"]
